### ISSUE TITLE
aanpassing van library bootstrap

### ISSUE THREAD

**Issue by Theo-denBlanken** [HHK3/frootje-bootstrappie#1]
+ Veel toepassingen gebruikt, 

- zou je ook nog iets kunnen aanpassen. Je gebruikt de class 'quote' terwijl het mooier zou zijn de class blockquote van Bootstrap zelf aan te passen!! : https://www.youtube.com/watch?v=qyxo5ZVWzAY

**Comment by HHK3** [comment]
Fixed
